# Generated by Django 3.2.16 on 2023-01-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20230103_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.folder'),
        ),
    ]
