# Generated by Django 3.2.16 on 2023-01-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20230103_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('crated_on', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shelf.category'),
        ),
    ]
