# Generated by Django 3.2.16 on 2023-01-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_auto_20230110_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='crated_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='crated_on',
            new_name='created_on',
        ),
    ]
