# Generated by Django 3.2.16 on 2023-01-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_auto_20230110_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-timestamp'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
