# Generated by Django 3.2.16 on 2023-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
